package views;

import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import logic.Dessert;
import logic.DessertHandler;
import logic.Pizza;
import logic.PizzaHandler;
import views.strategies.InsertPizzaStrategy;
import views.strategies.UpdatePizzaStrategy;

/**
 *
 * @author --G--
 */
public class MainForm extends javax.swing.JFrame {
    
    private AbstractTableModel pizzaTableModel;
    private List<Pizza> pizzas;
    private PizzaEventListener eventListener;
    private PizzaHandlerForm pizzaHandlerForm;
    private AbstractTableModel dessertTableModel;
    private List<Dessert> desserts;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        pizzas = PizzaHandler.getPizzaList();
        pizzaTableModel = new PizzaTableModel(pizzas);
        tblPizza.setModel(pizzaTableModel);
        eventListener = new PizzaListener();
        desserts = DessertHandler.getDessertList();
        dessertTableModel = new DessertTableModel(desserts);
        jTable1.setModel(dessertTableModel);
        tabPanel.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNew = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPizza = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btNew.setText("Új pizza");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        tblPizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPizzaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPizza);

        tabPanel.addTab("Pizzas", jScrollPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        tabPanel.addTab("Desserts", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNew)
                    .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btNew)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        long newId = calculateNewId();
        pizzaHandlerForm = new PizzaHandlerForm(this, newId);
        pizzaHandlerForm.addPizzaEventListener(eventListener);
        pizzaHandlerForm.setPizzaHandlingStrategy(new InsertPizzaStrategy());
        pizzaHandlerForm.setVisible(true);
        
    }//GEN-LAST:event_btNewActionPerformed
    
    private void tblPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPizzaMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() > 1) {
            int index = tblPizza.getSelectedRow();
            pizzaHandlerForm = new PizzaHandlerForm(this, pizzas.get(index));
            pizzaHandlerForm.addPizzaEventListener(eventListener);
            pizzaHandlerForm.setPizzaHandlingStrategy(new UpdatePizzaStrategy());
            pizzaHandlerForm.setVisible(true);
        }
    }//GEN-LAST:event_tblPizzaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    private long calculateNewId() {
        long newId = 1;
        if (!pizzas.isEmpty()) {
            //TODO: meg kene keresni a pizza listabol a legnagyobb id-t HW
            newId = pizzas.get(pizzas.size() - 1).
                    getId() + 1;
        }
        return newId;
    }
    
    private class PizzaListener implements PizzaEventListener {
        
        @Override
        public void pizzaCreated(Pizza newPizza) {
            pizzas.add(newPizza);
            drawTable();
        }
        
        @Override
        public void pizzaUpdated() {
            drawTable();
        }
        
        private void drawTable() {
            pizzaTableModel.fireTableDataChanged();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tblPizza;
    // End of variables declaration//GEN-END:variables
}
