package views;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import logic.Pizza;
import logic.PizzaHandler;

/**
 *
 * @author --G--
 */
public class PizzaHandlerForm extends javax.swing.JDialog {

    private Pizza pizza;
    private boolean update;
    private List<PizzaEventListener> listeners;
    private PizzaHandlingStrategy strategy;

    /**
     * Creates new form PizzaHandlerForm
     */
    public PizzaHandlerForm(java.awt.Frame parent, long newId) {
        super(parent, true);
        initComponents();
        listeners = new ArrayList<>();
        update = false;
        tfId.setText(String.valueOf(newId));
        pizza = new Pizza();
    }

    public PizzaHandlerForm(Frame frame, Pizza pizza) {
        this(frame, pizza.getId());
        this.pizza = pizza;
        update = true;
        fillFormFromPizza();
    }

    public void setPizzaHandlingStrategy(PizzaHandlingStrategy strategy) {
        this.strategy = strategy;
    }

    public void addPizzaEventListener(PizzaEventListener l) {
        listeners.add(l);
    }

    public void removePizzaEventListener(PizzaEventListener l) {
        listeners.remove(l);
    }

    private void notifyListeners() {
        for (PizzaEventListener listener : listeners) {
//            if (update) {
//                listener.pizzaUpdated();
//            } else {
//            listener.pizzaCreated(pizza);
//            }
            strategy.notify(pizza, listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfDiameter = new javax.swing.JTextField();
        cbSpicy = new javax.swing.JCheckBox();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Név");

        jLabel2.setText("Id");

        jLabel3.setText("Ár");

        jLabel5.setText("Átmérő");

        tfId.setEditable(false);

        cbSpicy.setText("Csípős");

        btSave.setText("Ment");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Kilép");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSpicy)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(cbSpicy)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        fillPizzaWithFormData();
//        if (update) {
//            PizzaHandler.updatePizza(pizza);
//        } else {
//            PizzaHandler.savePizza(pizza);
//        }
        strategy.save(pizza);
        notifyListeners();
        this.dispose();
    }//GEN-LAST:event_btSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JCheckBox cbSpicy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfDiameter;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables

    private void fillPizzaWithFormData() {
        pizza.setId(Long.parseLong(tfId.getText()));
        pizza.setName(tfName.getText());
        pizza.setPrice(Integer.parseInt(tfPrice.getText()));
        pizza.setDiameter(Integer.parseInt(tfDiameter.getText()));
        pizza.setSpicy(cbSpicy.isSelected());
    }

    private void fillFormFromPizza() {
        tfDiameter.setText(String.valueOf(pizza.getDiameter()));
        tfName.setText(pizza.getName());
        tfPrice.setText(String.valueOf(pizza.getPrice()));
        cbSpicy.setSelected(pizza.isSpicy());
        tfName.requestFocus();
        tfName.selectAll();
    }
}
